### ISSUE TITLE
Custom CSS for label

### ISSUE THREAD

**Issue by hakimihamdan88** [jan-vince/smallcontactform#38]
How do I custom control-label css class? seems cant find how to do it.

It should be similar like the custom CSS class.

**Comment by jan-vince** [comment]
Hi @hakimihamdan88 

there is no class definition for label itself, but when you assign CSS class for field container (````.form-control```` is default), you can easily control label.

Something like:

````css

.form-control label {
   color: red;
}

````
